# Generated by Django 4.2.27 on 2026-01-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200, verbose_name='ФИО врача')),
                ('clinic', models.CharField(max_length=300, verbose_name='Лечебное учреждение')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выписки')),
                ('expiry_date', models.DateField(verbose_name='Срок действия')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('used', 'Использованный'), ('expired', 'Просроченный'), ('pending', 'На рассмотрении')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено'), ('ready_for_pickup', 'Готов к выдаче')], default='processing', max_length=20)),
                ('pickup_point', models.CharField(max_length=300, verbose_name='Пункт выдачи')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0, verbose_name='Скидка %')),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к заказу')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.prescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название препарата')),
                ('dosage', models.CharField(max_length=100, verbose_name='Дозировка')),
                ('form', models.CharField(choices=[('tablets', 'Таблетки'), ('capsules', 'Капсулы'), ('injection', 'Инъекции'), ('ointment', 'Мазь'), ('drops', 'Капли'), ('syrup', 'Сироп'), ('spray', 'Спрей'), ('powder', 'Порошок')], max_length=50, verbose_name='Форма выпуска')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкция по применению')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='users.prescription')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
    ]
