# Generated by Django 4.2.27 on 2026-01-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prescription_order_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер рецепта (ID)'),
        ),
    ]
