# Generated by Django 5.1.4 on 2025-01-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default='Not', max_length=255, unique=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(default='Not', max_length=255)),
                ('recipient', models.CharField(default='Not', max_length=255)),
                ('sender_adres', models.CharField(default='Not', max_length=500)),
                ('recipient_adres', models.CharField(default='Not', max_length=500)),
            ],
        ),
    ]
